name: Release

on:
  push:
    tags: ["v*"]

jobs:
  test:
    name: ruby-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "4.0"
      - run: bundle exec rake
  push:
    name: Push gem to RubyGems.org
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "4.0"
      - uses: rubygems/release-gem@v1
